import type { Metadata } from "next";
import { Playfair, Nunito } from "next/font/google";
import "./globals.css";

const playfair = Playfair({
  weight: ["500", "600", "900"],
  variable: "--font-playfair",
  subsets: ["latin"],
  display: "swap",
});

const nunito = Nunito({
  weight: ["500", "700"],
  variable: "--font-nunito",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${nunito.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
